version: '3'

services:

  app:
    container_name: app
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./:/var/www/html/
    links:
      - mysql

  mysql:
    container_name: db
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db:
    driver: local